import 'package:flutter/material.dart';
import '../../domain/entities/calendar_event_entity.dart';
import '../../domain/usecases/calendar_usecases.dart';
import '../../../../core/errors/exceptions.dart';

enum CalendarStateStatus { initial, loading, loaded, creating, updating, deleting, error }

class GoogleCalendarProvider extends ChangeNotifier {
  final GetCalendarEvents _getEvents;
  final CreateCalendarEvent _createEvent;
  final UpdateCalendarEvent _updateEvent;
  final DeleteCalendarEvent _deleteEvent;

  CalendarStateStatus _status = CalendarStateStatus.initial;
  List<CalendarEventEntity> _events = [];
  String? _errorMessage;
  bool _isConnected = false;

  GoogleCalendarProvider({
    required GetCalendarEvents getEvents,
    required CreateCalendarEvent createEvent,
    required UpdateCalendarEvent updateEvent,
    required DeleteCalendarEvent deleteEvent,
  })  : _getEvents = getEvents,
        _createEvent = createEvent,
        _updateEvent = updateEvent,
        _deleteEvent = deleteEvent;

  CalendarStateStatus get status => _status;
  List<CalendarEventEntity> get events => _events;
  String? get errorMessage => _errorMessage;
  bool get isConnected => _isConnected;

  Future<void> loadEvents() async {
    _status = CalendarStateStatus.loading;
    _errorMessage = null;
    notifyListeners();

    try {
      _events = await _getEvents();
      _isConnected = true;
      _status = CalendarStateStatus.loaded;
    } catch (e) {
      _handleError(e);
    }
    notifyListeners();
  }

  Future<void> createTestEvent() async {
    _status = CalendarStateStatus.creating;
    _errorMessage = null;
    notifyListeners();

    try {
      final now = DateTime.now();
      final newEvent = CalendarEventEntity(
        id: '', // Will be generated by Google
        title: 'Flutter Google Calendar Integration Test',
        description: 'Temporary event created by the Flutter application for Google Calendar API integration testing.',
        start: now.add(const Duration(hours: 1)),
        end: now.add(const Duration(hours: 2)),
      );

      final created = await _createEvent(event: newEvent);
      _events.add(created);
      _status = CalendarStateStatus.loaded;
    } catch (e) {
      _handleError(e);
    }
    notifyListeners();
  }

  Future<void> updateTestEvent(CalendarEventEntity event) async {
    _status = CalendarStateStatus.updating;
    _errorMessage = null;
    notifyListeners();

    try {
      final updatedEvent = CalendarEventEntity(
        id: event.id,
        title: '${event.title} (Updated)',
        description: event.description,
        start: event.start,
        end: event.end?.add(const Duration(hours: 1)),
      );

      final result = await _updateEvent(event: updatedEvent);
      final index = _events.indexWhere((e) => e.id == result.id);
      if (index != -1) {
        _events[index] = result;
      }
      _status = CalendarStateStatus.loaded;
    } catch (e) {
      _handleError(e);
    }
    notifyListeners();
  }

  Future<void> deleteTestEvent(String eventId) async {
    _status = CalendarStateStatus.deleting;
    _errorMessage = null;
    notifyListeners();

    try {
      await _deleteEvent(eventId: eventId);
      _events.removeWhere((e) => e.id == eventId);
      _status = CalendarStateStatus.loaded;
    } catch (e) {
      _handleError(e);
    }
    notifyListeners();
  }

  void _handleError(dynamic error) {
    if (error is ServerException) {
      _errorMessage = error.message;
    } else {
      _errorMessage = error.toString();
    }
    
    // Check if it's an auth error based on typical string contents
    if (_errorMessage!.contains('not authenticated') || _errorMessage!.contains('access')) {
      _isConnected = false;
    }
    
    _status = CalendarStateStatus.error;
    debugPrint('[GoogleCalendar] Error: $_errorMessage');
  }
}
